// Model for job recommendations provided by recruiters or generated by AI

const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const recommendationSchema = new Schema({
  jobSeekerId: { type: Schema.Types.ObjectId, ref: 'User', required: true }, // Job seeker receiving the recommendation
  jobRecommendations: [{ type: Schema.Types.ObjectId, ref: 'JobPosting' }], // List of recommended jobs
  recruiterId: { type: Schema.Types.ObjectId, ref: 'User' }, // Optional: Recruiter who recommended
  candidateRecommendation: { type: String }, // Message or reason for recommendation
  generatedAt: { type: Date, default: Date.now }
});

const Recommendation = mongoose.model('Recommendation', recommendationSchema);
module.exports = Recommendation;
